---
   - name: Install nginx repo
     yum: name='http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm'

   - name: Install nginx package
     yum: name=nginx-1.8.0 state=present

   - name: Enable nginx autoload
     command: systemctl enable nginx

   - name: Copy nginx conf
     template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
     notify: reload nginx

   - name: Copy vhost conf
     template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/vhost.conf
     notify: reload nginx     

   - name: Start nginx
     service: name=nginx state=running enabled=true
   - file: path={{ vhosts_dir }}{{ domain }} state=directory owner={{ www_user }} group={{ www_user }} mode=0755
