---
   - name: Install Percona repo
     yum: name='http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm'

   - name: Install Percona packages
     yum: name={{ item }} state=present
     with_items:
        - Percona-Server-shared-56
        - Percona-Server-server-56
        - Percona-Server-client-56

   - name: Enable mysql autoload
     command: systemctl disable mysqld.service

   - name: Start mysql
     service: name=mysqld state=running enabled=true
