---
   - name: Install webtatic repo
     yum: name='https://mirror.webtatic.com/yum/el7/webtatic-release.rpm'

   - name: Install epel repo
     yum: name='https://mirror.webtatic.com/yum/el7/epel-release.rpm'

   - name: Install php56w packages
     yum: name={{ item }} state=present
     with_items:
       - php56w-5.6.8
       - php56w-mbstring
       - php56w-process
       - php56w-pecl-memcached
       - php56w-cli
       - php56w-opcache
       - php56w-pdo
       - php56w-mcrypt
       - php56w-gd
       - php56w-mysql
       - php56w-xml
       - php56w-pecl-memcache
       - php56w-pecl-igbinary
       - php56w-bcmath
       - php56w-common
       - php56w-fpm
       - php56w-pear
       - php56w-soap

   - name: Enable php-fpm autoload
     command: systemctl enable php-fpm

   - name: Copy conf
     template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf

   - name: Start php-fpm
     service: name=php-fpm state=running enabled=true
